In [95]:
import sys
sys.path.insert(0, '/home/jpmarceaux')
from jpq import *
import numpy as np
from qutip import ptrace, Qobj

https://quantumcomputing.stackexchange.com/questions/14264/nielsenchuang-5-qubit-quantum-error-correction-encoding-gate

In [14]:
class Gate():
    """
    n-qubit operator of either provided type or selected from pre-saved dictionary
    """
    def __init__(self, qbits, data, dtype):
        return 
    #!__init__

In [5]:
rho = State(np.eye(2))
rho.normalize()
html = rho.html()
f = open("test.html", "w")
f.write(html)

138

In [21]:
Mu = Measurement(4, dtype="stdbasis")
R = Register(2)
print(Mu.apply(R))

[(1+0j), 0j, 0j, 0j]


In [23]:
def TrX(p, sys, dim):
    """
    Calculate the partial trace over the specified systems with provided dimensions
    
    credit: http://www.dr-qubit.org/matlab/TrX.m
    """
    
    # check argument errors
    if(any(s > len(dim)-1 for s in sys) or any(s < 0 for s in sys)):
        raise ValueError("Invalid subsystem in SYS")
    if( (len(dim) == 1 and (len(p)/dim)%1 != 0) or len(p) != np.prod(dim) ):
        raise ValueError("Size of state PSI inconsistent with DIM")
    
    # remove singleton dimensions
    dim = [d for d in dim if d > 1]
    
    # calculate systems, dimensions, etc...
    n = len(dim)
    rdim = dim[::-1]
    keep = [r for r in range(n)]
    for s in sys:
        keep.remove(s)
    
    dimtrace = 1
    for s in sys:
        dimtrace = dimtrace*dim[s]
    dimkeep = len(p)/dimtrace
    
    # TODO: add support for state vectors
    
    # density matrix trace
    
    # reshape density matrix into tensor with one row and column index for each subsystem
    newshape = [d for d in dim+dim]
    ten = np.reshape(p, newshape)
    print(ten)
    # sum over the traced dimensions
    
    
    
    
    # reshape again so that first two indices are multi-indices of rows and columns that are kept 
    # and the third index is a flattened index for traced subsytems
    preperm = keep[::-1]+[k-n for k in keep[::-1]]+sys+[s-n for s in sys]
    perm = [n-pp-1 for pp in preperm]
    ten2 = np.reshape(ten.transpose(perm), [int(dimkeep), int(dimkeep), int(dimtrace**2)])
    print(ten2)
    
    # reshape density matrix into tensor with one row and one column index
    # for each subsystem, permute traced subssytem indices to the end, 
    # reshape again so that first two indices are row and column
    # multi-indices for kept sybsystem and third index is a flattened index
    # for traced subsystems, then sum third indeix over "diagonal" entries 

    x = np.sum(x[:, :, diag], 2)
    return 
#!TrX

[[[1. 0. 0. 1.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [1. 0. 0. 1.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [1. 0. 0. 1.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [1. 0. 0. 1.]]]


UnboundLocalError: local variable 'x' referenced before assignment

In [169]:
def TrX(p, sys, dim):
    """
    my partial trace function
    """
    sys = np.asarray(sys)
    dim = np.asarray(dim)
    assert np.prod(dim) == p.shape[0]
    Ndim = dim.size
    keep = [d for d in range(Ndim)]
    for s in sys:
        keep.remove(s)
    #xfor
    Nkeep = np.prod(dim[keep])
    
    # reshape into tensor with one row & col index for each subsystem
    rho = p.reshape(np.tile(dim, 2))
    
    # make permutation that takes traced subsystems to first positions
    perm = [i for i in range(Ndim)]
    for idx, s in enumerate(sys):
        if perm[idx] != s:
            perm[perm.index(s)] = perm[idx]
            perm[idx] = s
    #xfor 
    permp = [p+Ndim for p in perm]
    rho = np.transpose(rho, perm+permp)
    
    for s in sys:
        rho = np.trace(rho, axis1=0, axis2=int(len(rho.shape)/2) )
    #xrho
    return rho.reshape(Nkeep, Nkeep)
#!TrX

In [170]:
TrX(np.eye(2*3*4), [0,2], [2,3,4])

array([[8., 0., 0.],
       [0., 8., 0.],
       [0., 0., 8.]])

In [93]:
    
    
    idx1 = [i for i in range(Ndim)]
    idx2 = [Ndim+1 if i in keep else i for i in range(Ndim)]
    rho_a = p.reshape(np.tile(dim, 2))
    rho_a = np.einsum(rho_a, idx1+idx2)
    return rho_a.reshape(Nkeep, Nkeep)

ValueError: dimensions in operand 0 for collapsing index 'E' don't match (3 != 4)

In [96]:
def TrX(p, sys, dim):
    """
    
    """
    assert np.prod(dim) == p.shape[0]
    qob = Qobj(p, dims=dim)
    q = qob.ptrace(sys)
    return q.full()

ValueError: too many values to unpack (expected 2)

In [100]:
q = Qobj(np.eye(8), dims=[2,2,2])
print(q)

ValueError: too many values to unpack (expected 2)